### ISSUE TITLE
Have a checklist of all supported features for each version on the README

### ISSUE THREAD

**Issue by rwmb** [JoshQuake/BlenderTools#11]
I think it's useful for people coming from other versions of Blender or Unreal and are trying out 4.1+ and UE 5.4+ to have a list of supported features i.e. Exporting Meshes is supported on Blender 4.0, but Armature is not.

I spent some time trying to figure this one out thinking I was doing something wrong and there were no errors on Blender, until I decided to check the issues page.

Great work btw!

**Comment by JoshQuake** [comment]
True. I will update current release and the readme later today with known issues and close this when it's done.

Thanks for the suggestion!

**Comment by JoshQuake** [comment]
I added a list of supported versions. Does that satisfy your request? I feel like adding issues to the readme is redundant with the issues tab, though right now that's a little messy with some pending issues from Epic's repo.

I reread your post, are you having issues with exporting armatures in Send2UE in blender 4? Or was that in regard to the open UE2rigify issue?

**Comment by rwmb** [comment]
That is great, thanks!
