### ISSUE TITLE
Unreal to Blender and back to Unreal introduces Scaling issues

### ISSUE THREAD

**Issue by dav01d** [JoshQuake/BlenderTools#4]
As much as I want to love this tool, one thing that always held it back was the Unreal -> Blender -> Unreal pipeline of it.
Take the SK_Mannequin for example:
![image](https://github.com/JoshQuake/BlenderTools/assets/14636906/62fbdd4a-b628-42da-89ec-71a1cd087ed3)
If you go ahead and **Asset Actions > Export** this as an FBX
Bring it into Blender
and then use Send to Unreal to send it back to Unreal, you will get a mesh that is woefully deformed
![image](https://github.com/JoshQuake/BlenderTools/assets/14636906/9583bca8-63e3-47d6-bac9-d8b0e7d5bf4f)

You can see the Root scale is set to 0.01, with the Pelvis and other bones having moved 100X in units to compensate?

This doesn't happen if you just do a File > Export > FBX. The one caveat to doing a Blender 4.0/4.1 FBX Export is you need to disable the Empty from Object Types
![image](https://github.com/JoshQuake/BlenderTools/assets/14636906/ebaa7fa2-ad59-4c49-af16-f396ee256dd4)

Doing this will allow you to bring an FBX from Blender into Unreal, without any other changes, and scaling lining up nicely.

Why is that? What is Send to Unreal doing on export with the units/scaling? And why is Blender's default FBX export settings not do any of those scaling issues? Is there something we can disable in Send2Unreal to let us have a better experience?

Caveat: I get I should probably have used the other addon from Epic as well, but I just wanted to demonstrate how an asset from Unreal, to Blender via FBX, and back out, creates issues.

**Comment by JoshQuake** [comment]
When you export from unreal and import to Blender, it's scale is 0.01. The scale needs to be applied.
![image](https://github.com/JoshQuake/BlenderTools/assets/3147154/71d6c959-5c15-49dd-8456-4c5e5e4b8396)

**Comment by JoshQuake** [comment]
I'm going to assume this resolved the issue. Lmk if it didn't
